version: '3.0'
services:
  # Container containing application
  fecommerce:
    build: .
    container_name: fecommerce
    volumes:
      - .:/app
    ports:
      - 5000:5000
    command: gunicorn -w 4 -b 0:5000 "ecommerce:create_app()"
